// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vibylylkqsdouaeebpye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpYnlseWxrcXNkb3VhZWVicHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTQzMjYsImV4cCI6MjA2Mjg3MDMyNn0.RK7pisFphFRR2-B_GrB7GXYrUlyjLvpv_7JGyR9hSFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);